# Generated by Django 5.2.4 on 2025-08-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
    ]
