# Generated by Django 5.2.4 on 2025-08-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0002_alter_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
