# Generated by Django 5.2.4 on 2025-08-03 16:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0004_alter_company_logo_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_path',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
