# Generated by Django 5.2.4 on 2025-08-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0005_alter_resume_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file_path',
            new_name='file',
        ),
    ]
