# Generated by Django 5.2.4 on 2025-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0005_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
