# Generated by Django 5.2.4 on 2025-08-29 17:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentapp', '0008_resume_ai_analysis_resume_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='raw'),
        ),
    ]
